name: Build MicroNetCore
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v2

      - name: Setup netcore
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Install dependencies
        run: dotnet restore

      - name: Build netcore
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
          
      - name: Push imagen registry
        uses: azure/docker-login@v1
        with:
          login-server: goopen.azurecr.io
          username: goopen
          password: ${{ secrets.REGISTRY_SECRET }}
      - run: |
            docker build . -t goopen.azurecr.io/msstorage:prod-${{ github.run_number }}
            docker push goopen.azurecr.io/msstorage:prod-${{ github.run_number }}
