name: Build MicroNetCore
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout 
        uses: actions/checkout@v2

      - name: Setup netcore
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Install dependencies
        run: dotnet restore

      - name: Build netcore
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
          
      - name: Push imagen registry
        uses: azure/docker-login@v1
        with:
          login-server: registry.digitalocean.com
          username: e0259e347e0942509983dffb61cc619d33d1224a40116f0208e81687d306b9cf
          password: ${{ secrets.REGISTRY_SECRET }}
      - run: |
          docker build . -t registry.digitalocean.com/bmlabs/msstorage:dev-lastest
          docker push registry.digitalocean.com/bmlabs/msstorage:dev-lastest
